
fps = 60

tile-size = 64

[gameplay]

spawn-delay = 0.5
neighbors = [
  [-1, -1], [-1, 0], [-1, 1],
  [0, -1], [0, 1],
  [1, -1], [1, 0], [1, 1]
]

# Supplies/min
production-rate = 20

[gameplay.monster]

# Seconds
delay-base = 50
delay-range = 20

treasure-base = 0
treasure-range = 10

[gameplay.price]

training = 200
supply = 5
rest = 10

[physics]

collision-radius = 0.5
repulsion-factor = 0.125

[interface.sidebar]

width = 240
margin = 16

[colors]

# Pallete: https://coolors.co/17bebb-2e282a-cd5334-edb88b-fad8d6
#        + https://coolors.co/17bebb-2e282a-cd5334-edb88b-0a100d

tiffany-blue = [23, 190, 187, 255]
charleston-green = [46, 40, 42, 255]
dark-coral = [205, 83, 52, 255]
pale-gold = [237, 184, 139, 255]
pale-pink = [250, 216, 214, 255]
smoky-black = [10, 16, 13, 255]

