
root = "default"

[[tasks]]
id = "default"
typename = "selector"

  [[tasks]]
  id = "defend"
  typename = "defend"
  parent = "default"
  max-dist = 10

  [[tasks]]
  id = "this is fine"
  typename = "calmdown"
  parent = "default"

