
root = "default"

[[tasks]]
id = "default"
typename = "sequence"

  [[tasks]]
  id = "get rid"
  typename = "drop"
  parent = "default"

  [[tasks]]
  id = "go home"
  typename = "retire"
  parent = "default"
