
root = "default"

[[tasks]]
id = "default"
typename = "selector"

  [[tasks]]
  id = "work"
  typename = "sequence"
  parent = "default"
  
    [[tasks]]
    id = "motivated?"
    typename = "selector"
    parent = "work"

      [[tasks]]
      id = "rested"
      typename = "rested"
      parent = "motivated?"

      [[tasks]]
      id = "needs money"
      typename = "not"
      parent = "motivated?"

        [[tasks]]
        id = "enough?"
        typename = "hastreasure"
        parent = "needs money"
    
    [[tasks]]
    id = "find supply"
    typename = "selector"
    parent = "work"

      [[tasks]]
      id = "already has"
      typename = "supplied"
      parent = "find supply"

      [[tasks]]
      id = "needs to collect"
      typename = "collect"
      parent = "find supply"
    
    [[tasks]]
    id = "sell"
    typename = "sell"
    parent = "work"

  [[tasks]]
  id = "adventure"
  typename = "sequence"
  parent = "default"

    [[tasks]]
    id = "genki ka na?"
    typename = "rested"
    parent = "adventure"

    [[tasks]]
    id = "empty handed"
    typename = "not"
    parent = "adventure"
    
      [[tasks]]
      id = "check hands"
      typename = "supplied"
      parent = "empty handed"

    [[tasks]]
    id = "scavenge"
    typename = "scavenge"
    parent = "adventure"
  
  [[tasks]]
  id = "rest"
  typename = "sequence"
  parent = "default"

    [[tasks]]
    id = "has enough?"
    typename = "hastreasure"
    parent = "rest"

    [[tasks]]
    id = "go for it"
    typename = "rest"
    parent = "rest"
  
  [[tasks]]
  id = "giveup"
  typename = "wait"
  parent = "default"

