
treasure = 1000

[map]

width = 20
height = 20

tiles = """
####################\
####....######.#####\
#......######..#####\
#......##......#...#\
#......###.........#\
#........#.....##..#\
#..#..#..#.........#\
#..#..#..#......#..#\
#..#..#..#.....##..#\
#..#..#..#.....#...#\
#..............#...#\
#.......###........#\
#......###.........#\
#..................#\
#..###...#######...#\
#...##.....#####...#\
#....##.....#......#\
#..................#\
##.......####......#\
####################\
"""

[map.pallete]
"." = "plains"
"#" = "ruins"

[[settlements]]
pos = [4, 4]
role = "training"

[[settlements]]
pos = [11, 7]
role = "harvest"

[[settlements]]
pos = [18, 14]
role = "harvest"

[[settlements]]
pos = [13, 16]
role = "rest"

[[settlements]]
pos = [19, 8]
role = "rest"

[[settlements]]
pos = [18, 2]
role = "den"

[[settlements]]
pos = [15, 2]
role = "den"

[[settlements]]
pos = [7, 11]
role = "den"

[[settlements]]
pos = [7, 14]
role = "den"

