
[map]

width = 20
height = 20

tiles = """
####################\
####.....#.....#...#\
#......###.....#...#\
#......#.......#...#\
#......###.....#...#\
#........#.....#...#\
#..#..#..#.....#...#\
#..#..#..#.....#...#\
#..#..#..#.....#...#\
#..#..#..#.....#...#\
#..............#...#\
#........#.........#\
#........#.........#\
#..................#\
#..###.............#\
#..###.............#\
#..###.............#\
#..................#\
##.......####......#\
####################\
"""

[map.pallete]
"." = "plains"
"#" = "ruins"

[[settlements]]
pos = [3, 3]

[[settlements]]
pos = [11, 7]

[[settlements]]
pos = [15, 14]

[[settlements]]
pos = [13, 16]

[[settlements]]
pos = [16, 2]

